#!/bin/bash

#TODO adjust it to exam questionnaire

# This script will execute  scripts one after another
# when the enter key is pressed

# Declare an array to store the names of the  scripts
scripts=(
"./login --username andreane82 --passw e00f8e21a864de304a6c" 
"./healthcheck --format json" 
"./questionnaire --questionnaire_id QQ000 --format json"  
"./doAnswer --questionnaire_id QQ000 --question_id P01 --session_id 1234 --option_id P01A1 --format json"  
"./getsessionanswers --questionnaire_id QQ000 --session_id 1234 --format json"  
"./resetall"  
"./questionnaire_upd --source "../test/dummy_data_files/TrekkingClubQuestionnaire.json""  
"./questionnaire --questionnaire_id QQ000 --format json"
"./logout" 
)

# Loop through the array and execute each script
for script in "${scripts[@]}"
do
    # Run the script
    python $script
    # Wait for the enter key to be pressed before continuing
    read -p "Press enter to continue..."
done

