#!/bin/bash

#TODO adjust it to exam questionnaire

# This script will execute  scripts one after another
# when the enter key is pressed

# Declare an array to store the names of the  scripts
scripts=("./healthcheck --format json" 
"./questionnaire --questionnaire_id QQ000 --format json"  
"./doAnswer --questionnaire_id asper --question_id cfhx --session_id 1234 --option_id ipvk --format json"  
"./getsessionanswers --questionnaire_id asper --session_id 1234 --format json"  
"./resetall"  
"./questionnaire_upd --source "../test/dummy_data_files/fill_data.json""  
"./questionnaire --questionnaire_id QQ000 --format json"
)

# Loop through the array and execute each script
for script in "${scripts[@]}"
do
    # Run the script
    python $script
    # Wait for the enter key to be pressed before continuing
    read -p "Press enter to continue..."
done

